AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless API to CRUD Appointments.

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowMethods:
          - '*'
        AllowOrigins:
          - '*'
        AllowHeaders:
          - '*'
  Lambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: appointment.api::appointment.api.EntryPoint.LambdaEntryPoint::FunctionHandlerAsync
      Runtime: dotnetcore3.1
      CodeUri: ''
      Description: Appointments Scheduling System
      MemorySize: 256
      Timeout: 30
      Policies:
      Events:
        PostResource:
          Type: HttpApi
          Properties:
            ApiId: HttpApi

  DynamoDBTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: "appointment-state-store"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions: 
        - 
          AttributeName: "Id"
          AttributeType: "S"
          # Required for GlobalSecondaryIndex
        -
          AttributeName: "Email"
          AttributeType: "S"
        -
          AttributeName: "CreateDate"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "Id"
          KeyType: "HASH"

      GlobalSecondaryIndexes: 
        - 
          IndexName: "email-index"
          KeySchema: 
            - 
              AttributeName: "Email"
              KeyType: "HASH"
            -
              AttributeName: "CreateDate"
              KeyType: "RANGE"
          Projection: 
            ProjectionType: "ALL"